### ISSUE TITLE
Crashes upon injection

### ISSUE THREAD

**Issue by RwOnke** [luadebug/RustedAssaultCube#3]
Used lunarinjector

**Comment by luadebug** [comment]
![image](https://github.com/user-attachments/assets/762d94b7-0bd2-4830-a301-b0a7fd3b90d3)
![image](https://github.com/user-attachments/assets/05ed33ff-145e-4732-a14c-381a14a1391f)
![image](https://github.com/user-attachments/assets/3bab0bdf-ba3a-4689-aa5f-40f2f59f85c4)
![image](https://github.com/user-attachments/assets/9e116ecb-c109-4a8f-956e-7185e49d4418)
![image](https://github.com/user-attachments/assets/301dec5c-223f-4aeb-b4cc-9f5543a495bb)
@RwOnke 
Works fine for me. Can you try extreme injector?
I have tried mine own injector over it.
![image](https://github.com/user-attachments/assets/6943ed52-4fa6-4970-941e-15c4d02ec805)
![image](https://github.com/user-attachments/assets/a3516104-bcd5-427c-b657-f38ba94b8f9d)
It seems working for both builds of my injector. https://github.com/luadebug/RustedDLLInjector/releases/tag/1.0.0
If you want you can try compile this C++ proj https://github.com/pathetic/assaultcube-internal and inject it.

**Comment by luadebug** [comment]
Please if you still have issue - open issue again.

**Comment by nonlin** [comment]
Yeah causes a crash on injection here as well.

**Comment by luadebug** [comment]
Could you please provide logs? Did you use newest release? Does Fonts folder has SimHei font installed?
